server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://switchyard.proxy.rlwy.net:36188/railway
    username: root
    password: LsZxBqitFmFrzmtgItFwlgOZZtnyeTqn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/views/

  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
